# 注册服务的端口号
server:
  port: 7777

spring:
  application:
    # 服务名称
    name: Gemini-Gateway

eureka:
  client:
    # 注册服务器的地址：服务提供者和服务消费者都要依赖这个地址
    serviceUrl:
#      defaultZone: http://10.202.34.144:9002/eureka/
#      defaultZone: http://127.0.0.1:9001/eureka/
      defaultZone: http://114.215.243.48:9001/eureka/


# 日志输出控制
logging:
  level:
    root: INFO
    com.Y3.AnalyticsTeam.CT: DEBUG
