# 注册服务的端口号
server:
  port: 1091

spring:
  application:
    # 服务名称
    name: Cancer-service-task
  cloud:
    config:
      discovery:
        enabled: true
  datasource:
    url: jdbc:oracle:thin:@10.202.34.180:1521:YSDUAT06
    username: CT_DM_1
    password: CT_DM_1
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: oracle.jdbc.driver.OracleDriver
    filters: config,mergeStat
    maxActive: 20
    initialSize: 0
    maxWait: 60000
    minIdle: 0
    #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1 from dual
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    #dbc_connectionInitSqls: SET NAMES utf8mb4
    removeAbandoned: true
    removeAbandonedTimeout: 1800
    logAbandoned: true

eureka:
  client:
    # 注册服务器的地址：服务提供者和服务消费者都要依赖这个地址
    serviceUrl:
#      defaultZone: http://10.202.34.144:9002/eureka/
      defaultZone: http://114.215.243.48:9001/eureka/
#      defaultZone: http://127.0.0.1:9001/eureka/

#请求处理的超时时间
ribbon:
  ReadTimeout: 5000
#请求连接的超时时间
  ConnectTimeout: 5000
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 1

hystrix:
  command:
    default:
      execution:
        isolation.thread.timeoutInMilliseconds: 10000
        timeout.enabled: false

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.Y3.AnalyticsTeam.CT.Cancer.PO
  config-location: classpath:config/mybatis-config.xml


# 日志输出控制
logging:
  path: ./logs/Cancer_service_task.log
#  level:
    #root: INFO
    #org.springframework.security: INFO

jobs.initialDelay: 5000
jobs.fixedRate: 60000